#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PACKAGE_DIR=$(dirname "$SCRIPT_DIR")
COMPOSE_FILE=${COMPOSE_FILE:-"$PACKAGE_DIR/compose.yaml"}
COMPOSE_PROJECT=${COMPOSE_PROJECT:-shape-of-you-staging}
DEPLOY_ROOT=${DEPLOY_ROOT:-/opt/shape-of-you/staging}
RELEASES_DIR="$DEPLOY_ROOT/releases"
CURRENT_LINK="$DEPLOY_ROOT/current"
PREVIOUS_LINK="$DEPLOY_ROOT/previous"
RELEASE_ENV_INPUT=${1:-}
APP_HOST=staging.shape-of-you.ru
IDENTITY_HOST=identity.staging.shape-of-you.ru
CERT_NAME=shape-of-you-staging
bootstrap_started=false

if [ -z "$RELEASE_ENV_INPUT" ] || [ ! -f "$RELEASE_ENV_INPUT" ]; then
  printf '%s\n' "Usage: deploy.sh <release-env-file>" >&2
  exit 2
fi

# release.env is generated by the trusted deployment workflow and contains no
# credentials. Runtime secrets live in /etc/shape-of-you/staging/api.env.
# shellcheck disable=SC1090
. "$RELEASE_ENV_INPUT"

: "${RELEASE_ID:?RELEASE_ID is required}"
: "${API_IMAGE:?API_IMAGE is required}"
: "${API_DIGEST:?API_DIGEST is required}"
: "${EDGE_IMAGE:?EDGE_IMAGE is required}"
: "${EDGE_DIGEST:?EDGE_DIGEST is required}"
: "${CERTBOT_IMAGE:?CERTBOT_IMAGE is required}"
: "${CERTBOT_DIGEST:?CERTBOT_DIGEST is required}"
: "${ACME_EMAIL:?ACME_EMAIL is required}"
: "${PUBLIC_IPV4:?PUBLIC_IPV4 is required}"
: "${SCHEMA_BACKWARD_COMPATIBLE:?SCHEMA_BACKWARD_COMPATIBLE is required}"
: "${DEPLOYMENT_TOPOLOGY:?DEPLOYMENT_TOPOLOGY is required}"

case "$DEPLOYMENT_TOPOLOGY" in
  shared-ingress) COMPOSE_TOPOLOGY_FILE="$PACKAGE_DIR/compose.shared-ingress.yaml" ;;
  standalone) COMPOSE_TOPOLOGY_FILE="$PACKAGE_DIR/compose.standalone.yaml" ;;
  *)
    printf '%s\n' "Unsupported deployment topology: $DEPLOYMENT_TOPOLOGY" >&2
    exit 2
    ;;
esac

printf '%s\n' "$API_DIGEST" | grep -Eq '^sha256:[0-9a-f]{64}$'
printf '%s\n' "$EDGE_DIGEST" | grep -Eq '^sha256:[0-9a-f]{64}$'
printf '%s\n' "$CERTBOT_DIGEST" | grep -Eq '^sha256:[0-9a-f]{64}$'
printf '%s\n' "$RELEASE_ID" | grep -Eq '^[0-9a-f]{40}$'
printf '%s\n' "$ACME_EMAIL" |
  grep -Eq '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
printf '%s\n' "$PUBLIC_IPV4" |
  awk -F. 'NF == 4 { for (i = 1; i <= 4; i++) if ($i !~ /^[0-9]+$/ || $i > 255) exit 1; exit 0 } { exit 1 }'

mkdir -p "$RELEASES_DIR"
RELEASE_DIR="$RELEASES_DIR/$RELEASE_ID"
mkdir -p "$RELEASE_DIR"
install -m 0600 "$RELEASE_ENV_INPUT" "$RELEASE_DIR/release.env"

sh "$SCRIPT_DIR/vm-preflight.sh" "$RELEASE_DIR/release.env"

compose() {
  docker compose \
    --project-name "$COMPOSE_PROJECT" \
    --env-file "$RELEASE_DIR/release.env" \
    --file "$COMPOSE_FILE" \
    --file "$COMPOSE_TOPOLOGY_FILE" \
    "$@"
}

cleanup() {
  if [ "$bootstrap_started" = "true" ]; then
    compose rm --force --stop edge-bootstrap >/dev/null 2>&1 || true
  fi
}

trap cleanup EXIT HUP INT TERM

compose --profile operations pull

if ! compose run --rm --no-deps --entrypoint sh certbot -c \
  "test -s /etc/letsencrypt/live/$CERT_NAME/fullchain.pem && test -s /etc/letsencrypt/live/$CERT_NAME/privkey.pem"; then
  # Remove the old edge before bootstrap so standalone port ownership or the
  # shared-ingress alias has exactly one destination during first issuance.
  compose rm --force --stop edge
  compose --profile operations up --detach --wait --wait-timeout 45 edge-bootstrap
  bootstrap_started=true

  challenge_probe=shape-of-you-ingress-ready
  compose run --rm --no-deps --entrypoint sh certbot -c \
    "printf '%s' '$challenge_probe' > /var/www/certbot/$challenge_probe"

  for hostname in "$APP_HOST" "$IDENTITY_HOST"; do
    probe_response=$(curl --fail --silent --show-error \
      "http://$hostname/.well-known/acme-challenge/$challenge_probe")
    if [ "$probe_response" != "$challenge_probe" ]; then
      printf '%s\n' "The active ingress did not route HTTP for $hostname." >&2
      exit 1
    fi
  done

  compose run --rm --no-deps --entrypoint sh certbot -c \
    "rm -f /var/www/certbot/$challenge_probe"

  compose run --rm --no-deps certbot certonly \
    --non-interactive \
    --agree-tos \
    --no-eff-email \
    --email "$ACME_EMAIL" \
    --cert-name "$CERT_NAME" \
    --webroot \
    --webroot-path /var/www/certbot \
    --domain "$APP_HOST" \
    --domain "$IDENTITY_HOST"
fi

compose run --rm --no-deps \
  --entrypoint /usr/local/bin/install-shape-of-you-certificate \
  certbot

if [ "$bootstrap_started" = "true" ]; then
  compose rm --force --stop edge-bootstrap
  bootstrap_started=false
fi

compose --profile operations run --rm migrate
compose up --detach --wait --wait-timeout 90 api
compose run --rm --no-deps \
  --entrypoint /usr/local/bin/start-shape-of-you-edge edge --test
compose up --detach --wait --wait-timeout 90 --remove-orphans edge

api_container=$(compose ps --quiet api)
if [ -z "$api_container" ]; then
  printf '%s\n' 'API container was not found after startup.' >&2
  exit 1
fi

published_api_ports=$(docker inspect \
  --format '{{range $port, $bindings := .HostConfig.PortBindings}}{{if $bindings}}{{$port}} {{end}}{{end}}' \
  "$api_container")
if [ -n "$published_api_ports" ]; then
  printf '%s\n' "API unexpectedly publishes host port(s): $published_api_ports" >&2
  exit 1
fi

if ! RELEASE_ID="$RELEASE_ID" sh "$SCRIPT_DIR/smoke.sh"; then
  printf '%s\n' "Deployment smoke failed." >&2

  if [ "$SCHEMA_BACKWARD_COMPATIBLE" = "true" ] && [ -L "$CURRENT_LINK" ]; then
    previous_release=$(basename "$(readlink -f "$CURRENT_LINK")")
    printf '%s\n' "Attempting application rollback to $previous_release." >&2
    EXPECTED_DEPLOYMENT_TOPOLOGY="$DEPLOYMENT_TOPOLOGY" \
      RUN_WRITE_SMOKE=false sh "$SCRIPT_DIR/rollback.sh" "$previous_release"
  else
    printf '%s\n' \
      "Automatic rollback is disabled because schema compatibility is not confirmed." >&2
  fi

  exit 1
fi

old_current=
if [ -L "$CURRENT_LINK" ]; then
  old_current=$(readlink -f "$CURRENT_LINK")
fi

if [ -n "$old_current" ]; then
  ln -sfn "$old_current" "$PREVIOUS_LINK"
fi
ln -sfn "$RELEASE_DIR" "$CURRENT_LINK"

printf '%s\n' "Deployment $RELEASE_ID completed."
